python -u run_PatchTST.py \
  --task_name classification \
  --root_path ./dataset \
  --model PatchTST \
  --log_dir ./log \
  --data sleep_data \
  --num_class 3 \
  --patch_len 16 \
  --stride 8 \
  --seq_len 180 \
  --enc_in 2 \
  --e_layers 2 \
  --d_model 16 \
  --d_ff 64 \
   --batch_size 32 \
  --learning_rate 0.001 \
  --train_epochs 50 \
  --patience 10