python -u run_TimesNet.py \
  --task_name classification \
  --root_path ./dataset \
  --model TimesNet \
  --log_dir ./log/TimesNet \
  --data sleep_data \
  --num_class 3 \
  --seq_len 180 \
  --pred_len 0 \
  --top_k 2 \
  --enc_in 2 \
  --e_layers 2 \
  --d_model 16 \
  --d_ff 64 \
  --batch_size 64 \
  --learning_rate 0.001 \
  --train_epochs 50 \
  --patience 20